### ISSUE TITLE
While using Development Server backend calls are not working

### ISSUE THREAD

**Issue by shivaprasad223** [porscheinformatik/angular-spring-heroes#1]
Unable to work with UI development server as it is returning 404 while hitting http://localhost:4200/api/heroes service call.

**Comment by derkoe** [comment]
Did you start the dev server via `npm start` as documented? `ng serve` alone will not work because it is not proxying the backend.

**Comment by shivaprasad223** [comment]
Thanks for the response. yes i was using ng serve instead of npm start.  It was my mistake. 
Closing the issue.
